/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_plivo_WRAP_H_
#define SWIG_plivo_WRAP_H_

class SwigDirector_PlivoAppCallback : public PlivoAppCallback, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_PlivoAppCallback(JNIEnv *jenv);
    virtual ~SwigDirector_PlivoAppCallback();
    virtual void onStarted(char const *msg);
    virtual void onStopped(int restart);
    virtual void onLogin();
    virtual void onLogout();
    virtual void onLoginFailed();
    virtual void onDebugMessage(char const *msg);
    virtual void onIncomingCall(int callId, char const *sipCallId, char const *fromContact, char const *toContact, char const *header);
    virtual void onIncomingCallHangup(int callId, char const *sipCallId);
    virtual void onIncomingCallRejected(int callId, char const *sipCallId);
    virtual void onOutgoingCall(int callId, char const *sipCallId);
    virtual void onOutgoingCallRinging(int callId, char const *sipCallId);
    virtual void onOutgoingCallRejected(int callId, char const *sipCallId);
    virtual void onOutgoingCallAnswered(int callId, char const *sipCallId);
    virtual void onOutgoingCallHangup(int callId, char const *sipCallId);
    virtual void onOutgoingCallInvalid(int callId, char const *sipCallId);
    virtual void onIncomingDigitNotification(int digit);
public:
    bool swig_overrides(int n) {
      return (n < 16 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<16> swig_override;
};


#endif
